name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test HTML file
        run: test -f index.html

      - name: Build Docker image
        run: docker build -t cicd-demo:latest .

      - name: Test Docker container
        run: |
          docker run -d -p 8080:80 --name cicd-container cicd-demo:latest
          sleep 5
          curl http://localhost:8080

      - name: Stop Docker container
        run: docker stop cicd-container